### ISSUE TITLE
Size functions in @media

### ISSUE THREAD

**Issue by Ser-Gen** [assetsjs/postcss-assets#53]
I need to use `height(image)` in media features, but I can't.

```pcss
.Page--blank {
	@media screen and (min-height: height(image)) {
		background-size: cover;
	}
}
```
```css
@media screen and (min-height: height(image)) {
	.Page--blank {
		background-size: cover;
	}
}
```

I have workaround this with variable, but it not obvious:

```pcss
$imageHeight: height(image);

.Page--blank {
	@media screen and (min-height: $imageHeight) {
		background-size: cover;
	}
}
```
```css
@media screen and (min-height: 1200px) {
	.Page--blank {
		background-size: cover;
	}
}
```
