### ISSUE TITLE
Get negative image width/height

### ISSUE THREAD

**Issue by georgest** [assetsjs/postcss-assets#60]
How can I get image width or height with negative sign. For example I want to achieve this:

margin-left: -width('image.jpg');

But it is not rendered properly.

**Comment by borodean** [comment]
Hey @georgest! I see two ways of how to achieve that. It doesn't seem to me that any of this ways is perfectly clean though. Hope this could be made cleaner as soon as PostCSS exosystem develops.

**Option 1.** Use expression-reducing plugins (like [postcss-calc](https://github.com/postcss/postcss-calc)) to multiply the result by -1:

```js
postcss([
  require('postcss-assets'),
  require('postcss-calc'), // included after postcss-assets
]);
```

```css
body {
  margin-left: calc(-1 * width('image.jpg'));
}
```

The `calc()` expression gets reduced and the resulting CSS contains exactly what you want.

**Option 2.** Provide function with negative density argument:
```css
body {
  margin-left: width('image.jpg', -1);
}
```

This feels a little bit like a hack since that's clearly not the purpose of the density argument. However, since all it does is multiplies the dimension by itself it results in what you want.
