### ISSUE TITLE
How to use postcss-assets without special name `resolve` in css-files?

### ISSUE THREAD

**Issue by palegrow** [assetsjs/postcss-assets#62]
For example:

```css
body {
  background: url('foobar.jpg');
  background: url('icons/baz.png');
}
```

convert to

```css
body {
  background: url('/media/patterns/foobar.jpg');
  background: url('/images/icons/baz.png');
}
```

without `resolve`.
