### ISSUE TITLE
about the baseUrl

### ISSUE THREAD

**Issue by jpuncle** [assetsjs/postcss-assets#64]
My config:

```javascripts
option: {
      basePath: 'src/',
      baseUrl: '//x.autoimg.cn/www/'
}
```

My style:

```css
html {
  background: resolve("../img/bg.png");
}
```

My output:

```css
html {
  background: url('/x.autoimg.cn/www/index/img/bg.png');
}
```

**Expected:**

```css
html {
  background: url('//x.autoimg.cn/www/index/img/bg.png');
}
```
